### ISSUE TITLE
Wiki shows "no image"

### ISSUE THREAD

**Issue by CaptainDuck** [JaxkDev/VehiclesWiki#1]
Hello! The wiki starting from https://github.com/JaxkDev/Vehicles/wiki/Creation_Vehicles_1 until the end shows "No image" might be because the wiki has moved. I, for one is very enthusiastic about making my own vehicle with the plugin and it's kind of confusing without the images.

Thank you! :smile:

**Comment by JaxkDev** [comment]
They have indeed expired...
The guide itself is out of date for vehicles 0.1.0+
I will hopefully re write it all at some point with more resources.
In the meantime I’ll try and find the original images.

**Comment by CaptainDuck** [comment]
All right, thank you.

**Comment by JaxkDev** [comment]
Found some images however most are lost so slowly adding the model pictures into the wiki but Stage 7 & 8 Will remain blank as it is incompatible with v0.1.0+
