### ISSUE TITLE
Can't watch images

### ISSUE THREAD

**Issue by waraisan** [JaxkDev/VehiclesWiki#2]
Dear JaxkDev
Excuse me. I'm Japanese and I'm writing using Google Translate, so please forgive me that English may be strange.
Now, I can't see all the images in Stages 7 and 8 and the link in Step 1 in Stage8. I don't know without this, so please improve as soon as possible.
Thank you.

**Comment by JaxkDev** [comment]
Afternoon, stages 7 & 8 are not compatible with v0.2.x so they are not up to date and do not have permanent images.
