### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by rexetbandityt** [JaxkDev/VehiclesWiki#3]
BLANK.php download link is broken. Says file not found

**Comment by JaxkDev** [comment]
There is no Blank.php file…?

**Comment by rexetbandityt** [comment]
> 

In the wiki, according to their vehicles, there is a link to download the Blank.php file, but it does not work

**Comment by JaxkDev** [comment]
Then your looking at an extremely outdated part of the wiki.

**Comment by rexetbandityt** [comment]
> Then your looking at an extremely outdated part of the wiki.

Could you send a new part of the wiki?
